# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('season', models.CharField(max_length=10)),
                ('episode', models.CharField(max_length=10)),
                ('episode_name', models.CharField(max_length=1000)),
                ('rating', models.CharField(max_length=10)),
                ('raters', models.CharField(max_length=10)),
                ('synopsis', models.CharField(max_length=10000)),
                ('airdate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
