# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_rating', '0003_auto_20160706_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='showdetail',
            name='release',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='showdetail',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
