# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show_rating', '0005_auto_20160709_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodedetail',
            old_name='episode_name',
            new_name='episodeName',
        ),
        migrations.RenameField(
            model_name='episodedetail',
            old_name='episode',
            new_name='episodeNumber',
        ),
        migrations.RenameField(
            model_name='episodedetail',
            old_name='episode_title',
            new_name='episodeTitle',
        ),
        migrations.RenameField(
            model_name='seasondetail',
            old_name='show_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='seasondetail',
            old_name='total_episodes',
            new_name='totalEpisodes',
        ),
        migrations.RenameField(
            model_name='showdetail',
            old_name='imdb_id',
            new_name='imdbID',
        ),
        migrations.RenameField(
            model_name='showdetail',
            old_name='rating',
            new_name='imdbRating',
        ),
        migrations.RenameField(
            model_name='showdetail',
            old_name='raters',
            new_name='imdbVotes',
        ),
        migrations.RenameField(
            model_name='showdetail',
            old_name='release',
            new_name='released',
        ),
        migrations.RenameField(
            model_name='showdetail',
            old_name='total_seasons',
            new_name='totalSeasons',
        ),
        migrations.RemoveField(
            model_name='episodedetail',
            name='season',
        ),
        migrations.RemoveField(
            model_name='episodedetail',
            name='show_title',
        ),
        migrations.AddField(
            model_name='episodedetail',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='episodedetail',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='episodedetail',
            name='imdbID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='episodedetail',
            name='runTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='episodedetail',
            name='seasonNumber',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='show_rating.SeasonDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episodedetail',
            name='showTitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='show_rating.ShowDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasondetail',
            name='imdbID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
