# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_rating', '0006_auto_20160731_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodedetail',
            name='episodeName',
        ),
    ]
