# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_rating', '0007_remove_episodedetail_episodename'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodedetail',
            name='seasonNumber1',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='episodedetail',
            name='showTitle1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
