# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_rating', '0008_auto_20160804_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absentTitle', models.CharField(max_length=1000)),
            ],
        ),
    ]
