# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:29
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160710_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('code', ckeditor.fields.RichTextField()),
                ('coded_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Project Entries',
                'verbose_name': 'Project Entry',
                'ordering': ['-coded_on'],
            },
        ),
    ]
