# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160710_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('code', tinymce.models.HTMLField(blank=True, null=True)),
                ('coded_on', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
