# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 13:34
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-coded_on'], 'verbose_name': 'Project Entry', 'verbose_name_plural': 'Project Entries'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='code',
            field=django_markdown.models.MarkdownField(default='addedfromshell'),
            preserve_default=False,
        ),
    ]
