# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160719_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireme',
            name='number',
            field=models.CharField(default=datetime.datetime(2016, 7, 21, 19, 30, 17, 996323, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='coded_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 7, 21, 19, 30, 22, 155110, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='summary',
            field=models.TextField(default=datetime.datetime(2016, 7, 21, 19, 30, 25, 971295, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 7, 21, 19, 30, 29, 819123, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion',
            field=models.TextField(default=datetime.datetime(2016, 7, 21, 19, 30, 36, 285373, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
